//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bot
    {
        public int ID_Curator { get; set; }
        public int ID_User { get; set; }
        public int ID_Command { get; set; }
        public int ID_Message { get; set; }
    
        public virtual Command Command { get; set; }
        public virtual Curator Curator { get; set; }
        public virtual Message Message { get; set; }
        public virtual Users Users { get; set; }
    }
}
