//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curator()
        {
            this.Bot = new HashSet<Bot>();
            this.Speciality1 = new HashSet<Speciality>();
        }
    
        public int ID_Curator { get; set; }
        public string Namee { get; set; }
        public string SecondName { get; set; }
        public string Patronymic { get; set; }
        public string Number { get; set; }
        public string Email { get; set; }
        public string Speciality { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bot> Bot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Speciality> Speciality1 { get; set; }
    }
}
