//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGE
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EGE_SchoolEntities : DbContext
    {
        internal readonly IEnumerable<object> List;

        public EGE_SchoolEntities()
            : base("name=EGE_SchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bot> Bot { get; set; }
        public virtual DbSet<Command> Command { get; set; }
        public virtual DbSet<Curator> Curator { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<Tariff> Tariff { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
